# Generated by Django 3.0.7 on 2020-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=14)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
